// Observed-message overlay (Task #36).
//
// The user's directive: "augment the spell database with our own method of verifying
// variations of the cast messages for everything we encounter." This is that method.
//
// ─────────────────────────────────────────────────────────────────────────────
// WHAT IT DOES. As the buffs model folds the log (replay AND live), it feeds every
// player cast (`observeCast`) and every candidate message line (`observeMessage`) here.
// The overlay MINES the association between a message and the spell the player was casting
// when it appeared, keyed by (messageText, spellKey), and counts how often each pairing
// recurs. From those counts it derives a per-message VERDICT:
//
//   VERIFIED          — the message consistently follows exactly ONE spell (n≥2). A
//                       reliable identifier: seeing it proves that spell landed.
//   SHARED / GENERIC  — the message follows MULTIPLE spells (e.g. "You feel different."
//                       for every illusion, "You feel much faster." for four hastes). It
//                       can NOT name a spell on its own — resolution needs cast history.
//   CONTRADICTS-WIKI  — the observed pairing differs from spells.json's msg_* for that
//                       spell (the wiki is known-wrong in places — e.g. Symbol of Pinzarn,
//                       whose real landing route is a heal line, not its listed message).
//   UNKNOWN           — too few observations to judge (a single spell, n<2).
//
// ─────────────────────────────────────────────────────────────────────────────
// THE EFFECTIVE DB. `deriveCorrections()` turns the learned registry into a small set of
// corrections layered OVER spells.json (overlay WINS): a VERIFIED single-spell landing
// message the DB was missing becomes a learned msg_cast_on_you the parser/module can trust;
// a CONTRADICTS-WIKI message surfaces the disagreement. A future agent should consult the
// overlay before trusting a wiki message — a SHARED verdict means "don't trust this message
// to name a spell."
//
// ─────────────────────────────────────────────────────────────────────────────
// PERSISTENCE. The buffs module owns an instance; the overlay is serialized to userData
// (versioned JSON, debounced) so it accretes across sessions, and a committed BASELINE
// snapshot (src/main/data/messageOverlay.baseline.json, generated by
// scripts/gen-message-overlay.ts from the full log) ships so fresh installs benefit from
// day one. On startup the baseline is loaded, then the persisted user overlay is merged on
// top (user observations add to the baseline counts).
//
// ─────────────────────────────────────────────────────────────────────────────
// EVERY COUNT IS FILED UNDER THE SOURCE THAT PRODUCED IT, AND RE-FOLDING A SOURCE REPLACES
// ITS FILING (JOS-231). The mining is a FOLD — it runs over the whole log at every launch and
// produces exactly the same counts from the same bytes. What it is seeded with used to be a
// single flat pile: the committed baseline PLUS `<userData>/message-overlay.json`, which is what
// the last session's identical fold had already written. So each cold launch added the log's
// observations to a snapshot that already contained them: MEASURED 22 -> 44 -> 88 across three
// launches, doubling forever, and every derived verdict (n>=2 is VERIFIED) resting on counts that
// describe the number of times the app has STARTED rather than what the log says.
//
// The fix is bookkeeping, not a filter. `sources` is a bucket per origin — `merge()` files an
// import (the baseline, a persisted bucket) under its key, `beginSource(key)` DISCARDS that key's
// bucket and points subsequent observations at it, and `build()` sums the buckets. A re-fold of a
// log therefore REPLACES that log's contribution instead of adding to it, which makes mining
// idempotent by construction: fold the same bytes any number of times, get the same counts
// (`tests/messageOverlayIdempotence.test.mts` folds three simulated cold launches and demands
// byte-identical output).
//
// Two things it deliberately does NOT do. It does not drop the persisted seed — a bucket for a
// character you are not folding right now is knowledge nothing else can re-derive, and the seed is
// also the ONLY channel by which a user's own mined messages ever become parser corrections
// (`effectiveSpellDb` derives them from the seed, before the fold). And it does not dedupe by log
// position — an identity per observation would persist thousands of offsets to answer a question
// "which log was this from" already answers.

import type {
  MessageOverlay,
  OverlayMessage,
  OverlayVerdict,
  SpellEntry
} from '../../shared/types'
import { castOnOtherSuffix } from './spellDb'

/** Overlay schema version — bump to invalidate a stale on-disk snapshot. */
export const OVERLAY_VERSION = 1

/**
 * The bucket observations land in when nobody named a source. The app always names one
 * (`session.ts` calls `beginOverlaySource(characterId(ref))` before each character's fold);
 * this is for the generator script and the unit tests, which fold one log and never switch.
 */
export const DEFAULT_SOURCE = 'log'

/**
 * The bucket the COMMITTED baseline's counts are filed under. Lives here rather than in
 * `overlayPersistence.ts` because it is a source key like any other, and because that file needs
 * Electron — a Node test asserting what does and does not get persisted has to be able to name it.
 * Never a character id: a real one is `<Name>@<server>`.
 */
export const BASELINE_SOURCE = 'baseline'

/**
 * Anything the miner can absorb counts from — the committed baseline (a full `MessageOverlay`,
 * verdicts and all) or one persisted bucket. Only these three fields are ever read: a verdict is
 * DERIVED, never imported.
 */
export interface OverlayCounts {
  messages: readonly {
    text: string
    role: 'landing' | 'wearsOff'
    spells: readonly { spell: string; count: number }[]
  }[]
}

/** One source's raw counts — the REGISTER that is persisted, not the view that is served. */
export interface OverlaySourceCounts {
  /** Which origin produced these counts: a character id, or the committed baseline's key. */
  key: string
  messages: { text: string; role: 'landing' | 'wearsOff'; spells: { spell: string; count: number }[] }[]
}

/** The whole register: every bucket, plus the log instant the miner has observed through. */
export interface OverlayRegister {
  updatedAt: string
  sources: OverlaySourceCounts[]
}

/** One seed handed to a miner at construction: counts, and the source key they are filed under. */
export interface OverlaySeed {
  key: string
  counts: OverlayCounts | null | undefined
}

/**
 * The buckets worth writing to userData: everything except the committed baseline, which is
 * re-seeded from the bundle on every launch (persisting it would only make a staler second copy).
 */
export function persistableSources(register: OverlayRegister): OverlaySourceCounts[] {
  return register.sources.filter((s) => s.key !== BASELINE_SOURCE)
}

/** How long after a cast a message line is attributed to it (ms). Mirrors the landing window. */
const ASSOCIATION_WINDOW_MS = 6_000

/** Minimum observations before a message earns a non-UNKNOWN verdict. */
const MIN_OBSERVATIONS = 2

/** A pending cast the overlay may still associate messages with. */
interface RecentCast {
  spellKey: string
  spellDisplay: string
  ts: number
}

/** Accumulated per-(message) association counts. */
interface MessageRecord {
  text: string
  role: 'landing' | 'wearsOff'
  /** spellKey → { display, count } */
  bySpell: Map<string, { display: string; count: number }>
}

/** Canonical spell key: lowercase, trimmed, trailing Roman rank stripped (mirrors parser). */
const RANK_TAIL_RE = / (?:i|ii|iii|iv|v|vi|vii|viii|ix|x)$/i
function canonKey(name: string): string {
  return name.trim().replace(RANK_TAIL_RE, '').trim().toLowerCase()
}

/**
 * True when a log line is the cast-on-OTHER form of a wiki message — it ENDS WITH the
 * invariant suffix (the wiki's "Someone <suffix>", the log naming the real target). Mirrors
 * parser.matchCastOnOther's tail test so we don't misflag a named-target landing line as a
 * self-message contradiction.
 */
function messageMatchesOtherSuffix(text: string, suffix: string): boolean {
  const attach = suffix.startsWith("'s") ? '' : ' '
  const tail = attach + suffix
  return text.endsWith(tail) && text.length > tail.length
}

/**
 * Add per-spell counts into a record, keyed canonically. The ONE place counts are combined —
 * imports (`merge`) and the cross-bucket sum (`aggregate`) share it so they can never drift.
 */
function addCounts(rec: MessageRecord, spells: readonly { spell: string; count: number }[]): void {
  for (const sp of spells) {
    const key = canonKey(sp.spell)
    const cur = rec.bySpell.get(key)
    if (cur) cur.count += sp.count
    else rec.bySpell.set(key, { display: sp.spell, count: sp.count })
  }
}

/** One bucket's records as persistable counts, sorted so the file is stable and diffable. */
function bucketCounts(bucket: Map<string, MessageRecord>): OverlaySourceCounts['messages'] {
  return [...bucket.values()]
    .map((rec) => ({
      text: rec.text,
      role: rec.role,
      spells: [...rec.bySpell.values()]
        .map((s) => ({ spell: s.display, count: s.count }))
        .sort((a, b) => a.spell.localeCompare(b.spell))
    }))
    .sort((a, b) => a.text.localeCompare(b.text))
}

/** A derived verdict for one message, plus the wiki disagreement when there is one. */
interface VerdictResult {
  verdict: OverlayVerdict
  wikiConflict?: { spell: string; wikiText: string }
}

/**
 * The LANDING half of verdictFor: the message was unambiguously anchored to the single spell
 * `spellDisplay`, and the DB knows that spell. Split out of verdictFor only to keep each
 * function's branch count in range — the tests below run in the exact same order as before.
 *
 * A landing line can be the SELF form (msg_cast_on_you) OR the on-OTHER form (the
 * wiki's "Someone <suffix>" → the log names the target, so we match by suffix). If
 * the observed line matches EITHER wiki form for this spell, it is CONSISTENT with
 * the wiki — not a contradiction. Only a line matching NEITHER (while the spell was
 * unambiguously the anchor) is a genuine wiki inaccuracy (e.g. Symbol of Pinzarn).
 */
function landingVerdict(rec: MessageRecord, spellDisplay: string, dbSpell: SpellEntry): VerdictResult {
  const you = dbSpell.msgCastOnYou
  if (you && you === rec.text) return { verdict: 'verified' }
  const otherSuffix = dbSpell.msgCastOnOther ? castOnOtherSuffix(dbSpell.msgCastOnOther) : null
  if (otherSuffix && messageMatchesOtherSuffix(rec.text, otherSuffix)) {
    return { verdict: 'verified' }
  }
  // The DB has a self message for this spell but we observed a DIFFERENT self-shaped
  // line → contradiction. If the DB has NO self message at all, treat it as a newly
  // VERIFIED landing message (a variation the wiki simply omits), not a contradiction.
  if (you) return { verdict: 'contradicts-wiki', wikiConflict: { spell: spellDisplay, wikiText: you } }
  return { verdict: 'verified' }
}

/**
 * The mining accumulator + verdict derivation. Deliberately dependency-free and pure over
 * its inputs so it can run identically in a replay-only generator script and in the live
 * module. `spellsByKey` (from the DB) is used ONLY to detect wiki contradictions.
 */
export class MessageOverlayMiner {
  /**
   * sourceKey → (messageText → record). ONE BUCKET PER ORIGIN (JOS-231): imports keep the key
   * they were merged under, the fold writes into the key `beginSource` named, and `build()` sums
   * them. Insertion order is merge order then fold order, and every serialization sorts, so two
   * runs over the same inputs produce byte-identical output.
   */
  private sources = new Map<string, Map<string, MessageRecord>>()
  /** Which bucket `observeMessage` writes into — the log currently being folded. */
  private current = DEFAULT_SOURCE
  /** The most-recent cast(s) still inside the association window (newest last). */
  private recentCasts: RecentCast[] = []
  /**
   * THE NEWEST LOG INSTANT THIS MINER HAS OBSERVED, and the overlay's `updatedAt`. It used to be
   * `new Date().toISOString()` — a WALL-CLOCK read inside a PUBLISHED fold snapshot, found by
   * folding the identical bytes twice and diffing the results (JOS-208, whose checkpoint JOS-230
   * later removed; `tests/foldDeterminism.test.mts` is the audit that survives it): the two runs
   * built their overlay milliseconds apart and disagreed on every fixture, over a field that
   * describes nothing about either fold.
   *
   * It is now what it should always have been: the LOG's own clock. "Current as of this instant
   * in the log" is a statement about the observations the overlay is made of; "current as of when
   * this object happened to be built" is a statement about the reader. Zero before the first
   * observation — a merged baseline does NOT move it, because a merge carries counts and no
   * instants, and inventing one from the file it came from would be a wall clock with a longer
   * paper trail.
   */
  private lastObservedTs = 0
  /** DB spells keyed by canonical name (for contradiction detection); optional. */
  private readonly spellsByKey?: Map<string, SpellEntry>

  constructor(spellsByKey?: Map<string, SpellEntry>) {
    this.spellsByKey = spellsByKey
  }

  /** The bucket for `key`, created empty on first use. */
  private bucket(key: string): Map<string, MessageRecord> {
    let b = this.sources.get(key)
    if (!b) {
      b = new Map()
      this.sources.set(key, b)
    }
    return b
  }

  /**
   * START FOLDING `key`'s LOG — the whole of it, from the first byte (JOS-231).
   *
   * Whatever this source contributed before (a bucket restored from `<userData>` at startup, or
   * an earlier fold of the same log in this process) is DISCARDED here, because the fold that
   * follows is about to state it again. That is the entire idempotence argument: the counts a
   * source contributes are the counts its most recent complete fold produced, never a running
   * total of how many times we have read it.
   *
   * `Map.set` keeps an existing key's insertion position, so re-folding a seeded source does not
   * reorder the register. The open cast anchor is dropped too — a new log begins with no anchor.
   */
  beginSource(key: string): void {
    this.sources.set(key, new Map())
    this.current = key
    this.recentCasts = []
  }

  /** Record that the player began casting a spell (the association anchor). */
  observeCast(spellDisplay: string, ts: number): void {
    this.expire(ts)
    if (ts > this.lastObservedTs) this.lastObservedTs = ts
    this.recentCasts.push({ spellKey: canonKey(spellDisplay), spellDisplay, ts })
  }

  /**
   * Record a candidate message line and associate it with the recent cast — but ONLY when
   * the anchor is UNAMBIGUOUS: exactly one distinct spell was cast in the window. During a
   * Quick Buff burst or heavy combat, several casts share the window and we can't honestly
   * attribute a message to any one of them, so we SKIP (a coincidental pairing would poison
   * the verdict). This unambiguous-anchor rule is what keeps VERIFIED verdicts trustworthy —
   * a message that consistently follows a single-cast window really is that spell's message.
   * `role` distinguishes a landing message from a wears-off message.
   */
  observeMessage(text: string, ts: number, role: 'landing' | 'wearsOff'): void {
    this.expire(ts)
    if (ts > this.lastObservedTs) this.lastObservedTs = ts
    if (this.recentCasts.length === 0) return
    // Unambiguous anchor: all recent casts must be the SAME spell (a recast counts as one).
    const distinct = new Set(this.recentCasts.map((c) => c.spellKey))
    if (distinct.size !== 1) return
    const cast = this.recentCasts[this.recentCasts.length - 1]
    const into = this.bucket(this.current)
    let rec = into.get(text)
    if (!rec) {
      rec = { text, role, bySpell: new Map() }
      into.set(text, rec)
    }
    const s = rec.bySpell.get(cast.spellKey)
    if (s) s.count++
    else rec.bySpell.set(cast.spellKey, { display: cast.spellDisplay, count: 1 })
  }

  /** Drop casts that have aged out of the association window. */
  private expire(now: number): void {
    if (this.recentCasts.length === 0) return
    this.recentCasts = this.recentCasts.filter((c) => now - c.ts <= ASSOCIATION_WINDOW_MS)
  }

  /**
   * Merge imported counts INTO one bucket (additive WITHIN that bucket). `sourceKey` says where
   * they came from, and is what `beginSource` needs in order to replace them when that same
   * origin is folded again — merging the baseline and a persisted character under one key would
   * put the fold's own output back in the pile it is seeded from, which is the JOS-231 defect.
   */
  merge(counts: OverlayCounts | null | undefined, sourceKey: string): void {
    if (!counts) return
    const into = this.bucket(sourceKey)
    for (const m of counts.messages) {
      let rec = into.get(m.text)
      if (!rec) {
        rec = { text: m.text, role: m.role, bySpell: new Map() }
        into.set(m.text, rec)
      }
      addCounts(rec, m.spells)
    }
  }

  /** Every bucket's counts, sorted — what persistence writes and re-seeds from. */
  register(): OverlayRegister {
    const sources: OverlaySourceCounts[] = []
    for (const [key, bucket] of this.sources) sources.push({ key, messages: bucketCounts(bucket) })
    return { updatedAt: new Date(this.lastObservedTs).toISOString(), sources }
  }

  /** All buckets summed into one accumulator — the view every verdict is derived from. */
  private aggregate(): Map<string, MessageRecord> {
    const out = new Map<string, MessageRecord>()
    for (const bucket of this.sources.values()) {
      for (const rec of bucket.values()) {
        let agg = out.get(rec.text)
        if (!agg) {
          agg = { text: rec.text, role: rec.role, bySpell: new Map() }
          out.set(rec.text, agg)
        }
        addCounts(agg, [...rec.bySpell.values()].map((s) => ({ spell: s.display, count: s.count })))
      }
    }
    return out
  }

  /** Derive a message's verdict from its per-spell counts + the DB (for contradictions). */
  private verdictFor(rec: MessageRecord): VerdictResult {
    const spells = [...rec.bySpell.values()]
    const total = spells.reduce((a, s) => a + s.count, 0)
    const distinct = spells.length
    if (distinct >= 2) return { verdict: 'shared' }
    if (total < MIN_OBSERVATIONS) return { verdict: 'unknown' }
    // Exactly one spell, seen ≥2×: VERIFIED — unless it contradicts the wiki's msg_* for
    // that spell (the DB says this spell prints a DIFFERENT message for this role).
    const only = spells[0]
    const dbSpell = this.spellsByKey?.get(canonKey(only.display))
    if (dbSpell) {
      if (rec.role === 'landing') return landingVerdict(rec, only.display, dbSpell)
      // wears-off role.
      const wikiText = dbSpell.msgWearsOff
      if (wikiText && wikiText !== rec.text) {
        return { verdict: 'contradicts-wiki', wikiConflict: { spell: only.display, wikiText } }
      }
    }
    return { verdict: 'verified' }
  }

  /** Build the served/persisted overlay from the current accumulator. */
  build(): MessageOverlay {
    const messages: OverlayMessage[] = []
    const stats = { verified: 0, shared: 0, contradictions: 0, unknown: 0 }
    for (const rec of this.aggregate().values()) {
      const spells = [...rec.bySpell.values()]
        .map((s) => ({ spell: s.display, count: s.count }))
        .sort((a, b) => b.count - a.count || a.spell.localeCompare(b.spell))
      const total = spells.reduce((a, s) => a + s.count, 0)
      const { verdict, wikiConflict } = this.verdictFor(rec)
      messages.push({ text: rec.text, role: rec.role, verdict, spells, total, wikiConflict })
      if (verdict === 'verified') stats.verified++
      else if (verdict === 'shared') stats.shared++
      else if (verdict === 'contradicts-wiki') stats.contradictions++
      else stats.unknown++
    }
    // Densest / most-informative first: contradictions, then verified, then shared, then
    // unknown; within a class by total observations desc.
    const rank: Record<OverlayVerdict, number> = {
      'contradicts-wiki': 0,
      verified: 1,
      shared: 2,
      unknown: 3
    }
    messages.sort((a, b) => rank[a.verdict] - rank[b.verdict] || b.total - a.total || a.text.localeCompare(b.text))
    return {
      version: OVERLAY_VERSION,
      // THE LOG'S CLOCK, NOT THE MACHINE'S — see `lastObservedTs` for the divergence that moved it.
      updatedAt: new Date(this.lastObservedTs).toISOString(),
      messages,
      stats
    }
  }

  /**
   * Derive the EFFECTIVE-DB corrections (overlay wins over spells.json). Returns a map of
   * messageText → the single spell it VERIFIABLY identifies, for landing messages the DB
   * either omits or gets wrong. A SHARED message yields no correction (it can't name a
   * spell). A CONTRADICTS-WIKI message yields a correction pointing at the OBSERVED spell.
   *
   * We ONLY emit a correction for a SELF-shaped message — one that does NOT end with any
   * spell's cast-on-other SUFFIX (those name a mob target, not the player, so registering
   * them as msg_cast_on_you would wrongly fire a self buffApply for a debuff-on-a-mob line).
   * The self test uses the DB's own cast-on-other suffixes, so it needs the DB (a miner
   * built without one emits no corrections — correct: nothing to correct against).
   */
  deriveLandingCorrections(): Map<string, { spell: string; contradicts?: string }> {
    const out = new Map<string, { spell: string; contradicts?: string }>()
    const built = this.build()
    for (const m of built.messages) {
      if (m.role !== 'landing') continue
      if (this.looksCastOnOther(m.text)) continue
      if (m.verdict === 'verified') {
        out.set(m.text, { spell: m.spells[0].spell })
      } else if (m.verdict === 'contradicts-wiki' && m.wikiConflict) {
        out.set(m.text, { spell: m.spells[0].spell, contradicts: m.wikiConflict.spell })
      }
    }
    return out
  }

  /** True when a line ends with ANY DB cast-on-other suffix (⇒ it names a mob, not self). */
  private looksCastOnOther(text: string): boolean {
    if (!this.spellsByKey) return false
    for (const s of this.spellsByKey.values()) {
      if (!s.msgCastOnOther) continue
      const suf = castOnOtherSuffix(s.msgCastOnOther)
      if (suf && messageMatchesOtherSuffix(text, suf)) return true
    }
    return false
  }
}
